spring:
  #Security
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://localhost:8080/realms/demo/protocol/openid-connect/certs
  #Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/boaz-test?createDatabaseIfNotExist=true
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

#eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

