spring:
  #Security
    security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/BoazReaml
          jwk-set-uri: http://localhost:8080/realms/BoazReaml/protocol/openid-connect/certs
  
  #Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/boaz-test?createDatabaseIfNotExist=true
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

# JWT Configuration
jwt:
  auth:
    converter:
      resource-id: boazClient
      principal-attribute: principal_username

#eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

